/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function FullKeyboard({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/26H3wAsvUmaVhibw/scene.splinecode')
  return (
    <>
      <group {...props} dispose={null}>
        <scene name="Scene 1">
          <group name="Group 2" position={[145.88, 266.82, -293.51]}>
            <group name="Group">
              <mesh
                name="Text"
                geometry={nodes.Text.geometry}
                material={materials['Text Material']}
                castShadow
                receiveShadow
                position={[51.23, 31.18, 3.29]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={[1, 1, 0.7]}
              />
              <mesh
                name="Cube"
                geometry={nodes.Cube.geometry}
                material={materials['Cube Material']}
                castShadow
                receiveShadow
                position={[0, -0.93, -25.79]}
                rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
                scale={[1, 1, 1.63]}
              />
            </group>
          </group>
          <group name="Top Row 5" position={[392.79, 262.31, -318.54]}>
            <group name="Master Key Instance 12" position={[-703.42, 0, 0]}>
              <group name="Cap">
                <mesh
                  name="Text1"
                  geometry={nodes.Text1.geometry}
                  material={materials['Text1 Material']}
                  castShadow
                  receiveShadow
                  position={[9.13, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube1"
                  geometry={nodes.Cube1.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[26.4, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 15" position={[-1003.19, 0, 0]}>
              <group name="Cap1">
                <mesh
                  name="Text2"
                  geometry={nodes.Text2.geometry}
                  material={materials['Text2 Material']}
                  castShadow
                  receiveShadow
                  position={[48.17, 34.74, 9.06]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube2"
                  geometry={nodes.Cube2.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[43.01, 15.19, 0]}
                  scale={[1.9, 1, 1]}
                />
              </group>
            </group>
            <group name="Master Key Instance 19" position={[487.55, 0, 0]}>
              <group name="Cap2" visible={false}>
                <mesh
                  name="Text3"
                  geometry={nodes.Text3.geometry}
                  material={materials['Text3 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube3"
                  geometry={nodes.Cube3.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 13" position={[375.48, 0, 0]}>
              <group name="Cap3" visible={false}>
                <mesh
                  name="Text4"
                  geometry={nodes.Text4.geometry}
                  material={materials['Text4 Material']}
                  visible={false}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube4"
                  geometry={nodes.Cube4.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 9" position={[372.32, 0, 0]}>
              <group name="Cap4" position={[-105.13, 0, 0]}>
                <mesh
                  name="Text5"
                  geometry={nodes.Text5.geometry}
                  material={materials['Text5 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube5"
                  geometry={nodes.Cube5.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 7" position={[267.39, 0, 0]}>
              <group name="Cap5" position={[-108.6, 0, 0]}>
                <mesh
                  name="Text6"
                  geometry={nodes.Text6.geometry}
                  material={materials['Text6 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube6"
                  geometry={nodes.Cube6.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
          </group>
          <group name="Top Row 4" position={[392.79, 262.31, -436.3]}>
            <group name="Master Key Instance 24" position={[-803.2, 0, 214.08]}>
              <group name="Cap6" position={[0, 0, -96.84]}>
                <mesh
                  name="Text7"
                  geometry={nodes.Text7.geometry}
                  material={materials['Text7 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube7"
                  geometry={nodes.Cube7.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[2, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 18" position={[-803.2, 0, 96.01]}>
              <group name="Cap7" position={[0, 0, -96.84]}>
                <mesh
                  name="Text8"
                  geometry={nodes.Text8.geometry}
                  material={materials['Text8 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube8"
                  geometry={nodes.Cube8.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[2, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 121" position={[-697.87, 0, 0]}>
              <group name="Cap8">
                <mesh
                  name="Text9"
                  geometry={nodes.Text9.geometry}
                  material={materials['Text9 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube9"
                  geometry={nodes.Cube9.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[2, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 11" position={[-590.88, 0, 0]}>
              <group name="Cap9">
                <mesh
                  name="Text10"
                  geometry={nodes.Text10.geometry}
                  material={materials['Text10 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube10"
                  geometry={nodes.Cube10.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 2" position={[-480.89, 0, 0]}>
              <group name="Cap10">
                <mesh
                  name="Text11"
                  geometry={nodes.Text11.geometry}
                  material={materials['Text11 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube11"
                  geometry={nodes.Cube11.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 151" position={[-1003.19, 0, 0]}>
              <group name="Cap11">
                <mesh
                  name="Text12"
                  geometry={nodes.Text12.geometry}
                  material={materials['Text12 Material']}
                  castShadow
                  receiveShadow
                  position={[48.17, 34.74, 9.06]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube12"
                  geometry={nodes.Cube12.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[43.01, 15.19, 0]}
                  scale={[1.9, 1, 1]}
                />
              </group>
            </group>
            <group name="Master Key Instance 20" position={[377.59, 0, 0]}>
              <group name="Cap12">
                <mesh
                  name="Text13"
                  geometry={nodes.Text13.geometry}
                  material={materials['Text13 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube13"
                  geometry={nodes.Cube13.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 23" position={[378.37, 0, 115.13]}>
              <group name="Cap13">
                <mesh
                  name="Text14"
                  geometry={nodes.Text14.geometry}
                  material={materials['Text14 Material']}
                  castShadow
                  receiveShadow
                  position={[22.31, 33.61, 24.08]}
                  rotation={[-0.03, 0, -0.03]}
                />
                <mesh
                  name="Cube14"
                  geometry={nodes.Cube14.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 22" position={[603.43, 0, 115.13]}>
              <group name="Cap14">
                <mesh
                  name="Text15"
                  geometry={nodes.Text15.geometry}
                  material={materials['Text15 Material']}
                  castShadow
                  receiveShadow
                  position={[27.21, 36.13, 19.05]}
                  rotation={[-0.03, 0, 0.03]}
                />
                <mesh
                  name="Cube15"
                  geometry={nodes.Cube15.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 21" position={[490.59, 0, 115.13]}>
              <group name="Cap15">
                <mesh
                  name="Text16"
                  geometry={nodes.Text16.geometry}
                  material={materials['Text16 Material']}
                  castShadow
                  receiveShadow
                  position={[21.28, 34.74, 17.68]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube16"
                  geometry={nodes.Cube16.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 191" position={[490.59, 0, 0]}>
              <group name="Cap16">
                <mesh
                  name="Text17"
                  geometry={nodes.Text17.geometry}
                  material={materials['Text17 Material']}
                  castShadow
                  receiveShadow
                  position={[25.67, 38.38, 19.33]}
                  rotation={[-1.29, -0.07, 0.01]}
                  scale={1}
                />
                <mesh
                  name="Cube17"
                  geometry={nodes.Cube17.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 17" position={[605.92, 0, 0]}>
              <group name="Cap17">
                <mesh
                  name="Text18"
                  geometry={nodes.Text18.geometry}
                  material={materials['Text18 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube18"
                  geometry={nodes.Cube18.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 131" position={[375.48, 0, 0]}>
              <group name="Cap18" visible={false}>
                <mesh
                  name="Text19"
                  geometry={nodes.Text19.geometry}
                  material={materials['Text19 Material']}
                  visible={false}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube19"
                  geometry={nodes.Cube19.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 10" position={[373.08, 0, 0]}>
              <group name="Cap19" visible={false}>
                <mesh
                  name="Text20"
                  geometry={nodes.Text20.geometry}
                  material={materials['Text20 Material']}
                  castShadow
                  receiveShadow
                  position={[19.13, 34.74, 19.44]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube20"
                  geometry={nodes.Cube20.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[61.29, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 91" position={[372.32, 0, 0]}>
              <group name="Cap20" position={[-105.13, 0, 0]}>
                <mesh
                  name="Text21"
                  geometry={nodes.Text21.geometry}
                  material={materials['Text21 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube21"
                  geometry={nodes.Cube21.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 8" position={[159.32, 0, 0]}>
              <group name="Cap21" position={[-214.76, 0, 0]}>
                <mesh
                  name="Text22"
                  geometry={nodes.Text22.geometry}
                  material={materials['Text22 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube22"
                  geometry={nodes.Cube22.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 71" position={[267.39, 0, 0]}>
              <group name="Cap22" position={[-108.6, 0, 0]}>
                <mesh
                  name="Text23"
                  geometry={nodes.Text23.geometry}
                  material={materials['Text23 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube23"
                  geometry={nodes.Cube23.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 6" position={[49.35, 0, -0.02]}>
              <group name="Cap23">
                <mesh
                  name="Text24"
                  geometry={nodes.Text24.geometry}
                  material={materials['Text24 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube24"
                  geometry={nodes.Cube24.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 4" position={[-160.79, 0, 0]}>
              <group name="Cap24">
                <mesh
                  name="Text25"
                  geometry={nodes.Text25.geometry}
                  material={materials['Text25 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube25"
                  geometry={nodes.Cube25.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 3" position={[-266.67, 0, 0]}>
              <group name="Cap25">
                <mesh
                  name="Text26"
                  geometry={nodes.Text26.geometry}
                  material={materials['Text26 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube26"
                  geometry={nodes.Cube26.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance" position={[-374.19, 0, 0]}>
              <group name="Cap26">
                <mesh
                  name="Text27"
                  geometry={nodes.Text27.geometry}
                  material={materials['Text27 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube27"
                  geometry={nodes.Cube27.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
          </group>
          <group name="Top Row 3" position={[392.79, 262.31, -551.53]}>
            <group name="Master Key Instance 122" position={[-803.2, 0, 0]}>
              <group name="Cap27">
                <mesh
                  name="Text28"
                  geometry={nodes.Text28.geometry}
                  material={materials['Text28 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube28"
                  geometry={nodes.Cube28.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[2, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 111" position={[-696.21, 0, 0]}>
              <group name="Cap28">
                <mesh
                  name="Text29"
                  geometry={nodes.Text29.geometry}
                  material={materials['Text29 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube29"
                  geometry={nodes.Cube29.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 25" position={[-586.22, 0, 0]}>
              <group name="Cap29">
                <mesh
                  name="Text30"
                  geometry={nodes.Text30.geometry}
                  material={materials['Text30 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube30"
                  geometry={nodes.Cube30.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 152" position={[-1003.19, 0, 0]}>
              <group name="Cap30">
                <mesh
                  name="Text31"
                  geometry={nodes.Text31.geometry}
                  material={materials['Text31 Material']}
                  castShadow
                  receiveShadow
                  position={[48.17, 34.74, 9.06]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube31"
                  geometry={nodes.Cube31.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[43.01, 15.19, 0]}
                  scale={[1.9, 1, 1]}
                />
              </group>
            </group>
            <group name="Master Key Instance 16" position={[604.88, 0, 0]}>
              <group name="Cap31">
                <mesh
                  name="Text32"
                  geometry={nodes.Text32.geometry}
                  material={materials['Text32 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube32"
                  geometry={nodes.Cube32.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 132" position={[375.48, 0, 0]}>
              <group name="Cap32">
                <mesh
                  name="Text33"
                  geometry={nodes.Text33.geometry}
                  material={materials['Text33 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube33"
                  geometry={nodes.Cube33.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 101" position={[267.75, 0, 0]}>
              <group name="Cap33">
                <mesh
                  name="Text34"
                  geometry={nodes.Text34.geometry}
                  material={materials['Text34 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube34"
                  geometry={nodes.Cube34.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 92" position={[266.99, 0, 0]}>
              <group name="Cap34" position={[-105.13, 0, 0]} scale={1}>
                <mesh
                  name="Text35"
                  geometry={nodes.Text35.geometry}
                  material={materials['Text35 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube35"
                  geometry={nodes.Cube35.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 81" position={[53.99, 0, 0]}>
              <group name="Cap35" position={[-214.76, 0, 0]}>
                <mesh
                  name="Text36"
                  geometry={nodes.Text36.geometry}
                  material={materials['Text36 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube36"
                  geometry={nodes.Cube36.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 72" position={[162.06, 0, 0]}>
              <group name="Cap36" position={[-108.6, 0, 0]}>
                <mesh
                  name="Text37"
                  geometry={nodes.Text37.geometry}
                  material={materials['Text37 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube37"
                  geometry={nodes.Cube37.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 61" position={[-55.98, 0, -0.02]}>
              <group name="Cap37">
                <mesh
                  name="Text38"
                  geometry={nodes.Text38.geometry}
                  material={materials['Text38 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube38"
                  geometry={nodes.Cube38.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 41" position={[-266.12, 0, 0]}>
              <group name="Cap38">
                <mesh
                  name="Text39"
                  geometry={nodes.Text39.geometry}
                  material={materials['Text39 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube39"
                  geometry={nodes.Cube39.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 31" position={[-372, 0, 0]}>
              <group name="Cap39">
                <mesh
                  name="Text40"
                  geometry={nodes.Text40.geometry}
                  material={materials['Text40 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube40"
                  geometry={nodes.Cube40.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance1" position={[-479.51, 0, 0]}>
              <group name="Cap40">
                <mesh
                  name="Text41"
                  geometry={nodes.Text41.geometry}
                  material={materials['Text41 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube41"
                  geometry={nodes.Cube41.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
          </group>
          <group name="Top Row 2" position={[392.79, 262.31, -663.19]}>
            <group name="Master Key Instance 123" position={[-803.2, 0, 0]}>
              <group name="Cap41">
                <mesh
                  name="Text42"
                  geometry={nodes.Text42.geometry}
                  material={materials['Text42 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube42"
                  geometry={nodes.Cube42.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 112" position={[-696.21, 0, 0]}>
              <group name="Cap42">
                <mesh
                  name="Text43"
                  geometry={nodes.Text43.geometry}
                  material={materials['Text43 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube43"
                  geometry={nodes.Cube43.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 26" position={[-586.22, 0, 0]}>
              <group name="Cap43">
                <mesh
                  name="Text44"
                  geometry={nodes.Text44.geometry}
                  material={materials['Text44 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube44"
                  geometry={nodes.Cube44.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 153" position={[-1003.19, 0, 0]}>
              <group name="Cap44">
                <mesh
                  name="Text45"
                  geometry={nodes.Text45.geometry}
                  material={materials['Text45 Material']}
                  castShadow
                  receiveShadow
                  position={[48.17, 34.74, 9.06]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube45"
                  geometry={nodes.Cube45.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[43.01, 15.19, 0]}
                  scale={[1.9, 1, 1]}
                />
              </group>
            </group>
            <group name="Master Key Instance 14" position={[482.4, 0, 0]}>
              <group name="Cap45">
                <mesh
                  name="Text46"
                  geometry={nodes.Text46.geometry}
                  material={materials['Untitled Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube46"
                  geometry={nodes.Cube46.geometry}
                  material={materials['Key Emphasis']}
                  castShadow
                  receiveShadow
                  position={[5.54, 15.19, 53.17]}
                  scale={[1.15, 1, 1]}
                />
              </group>
            </group>
            <group name="Master Key Instance 161" position={[604.88, 0, 0]}>
              <group name="Cap46">
                <mesh
                  name="Text47"
                  geometry={nodes.Text47.geometry}
                  material={materials['Text47 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube47"
                  geometry={nodes.Cube47.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 133" position={[375.48, 0, 0]}>
              <group name="Cap47">
                <mesh
                  name="Text48"
                  geometry={nodes.Text48.geometry}
                  material={materials['Text48 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube48"
                  geometry={nodes.Cube48.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 102" position={[267.75, 0, 0]}>
              <group name="Cap48">
                <mesh
                  name="Text49"
                  geometry={nodes.Text49.geometry}
                  material={materials['Text49 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube49"
                  geometry={nodes.Cube49.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 93" position={[266.99, 0, 0]}>
              <group name="Cap49" position={[-105.13, 0, 0]}>
                <mesh
                  name="Text50"
                  geometry={nodes.Text50.geometry}
                  material={materials['Text50 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube50"
                  geometry={nodes.Cube50.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 82" position={[53.99, 0, 0]}>
              <group name="Cap50" position={[-214.76, 0, 0]}>
                <mesh
                  name="Text51"
                  geometry={nodes.Text51.geometry}
                  material={materials['Text51 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube51"
                  geometry={nodes.Cube51.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 73" position={[162.06, 0, 0]}>
              <group name="Cap51" position={[-108.6, 0, 0]}>
                <mesh
                  name="Text52"
                  geometry={nodes.Text52.geometry}
                  material={materials['Text52 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube52"
                  geometry={nodes.Cube52.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 62" position={[-55.98, 0, -0.02]}>
              <group name="Cap52">
                <mesh
                  name="Text53"
                  geometry={nodes.Text53.geometry}
                  material={materials['Text53 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube53"
                  geometry={nodes.Cube53.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 42" position={[-266.12, 0, 0]}>
              <group name="Cap53">
                <mesh
                  name="Text54"
                  geometry={nodes.Text54.geometry}
                  material={materials['Text54 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube54"
                  geometry={nodes.Cube54.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 32" position={[-372, 0, 0]}>
              <group name="Cap54">
                <mesh
                  name="Text55"
                  geometry={nodes.Text55.geometry}
                  material={materials['Text55 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube55"
                  geometry={nodes.Cube55.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance2" position={[-479.51, 0, 0]}>
              <group name="Cap55">
                <mesh
                  name="Text56"
                  geometry={nodes.Text56.geometry}
                  material={materials['Text56 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube56"
                  geometry={nodes.Cube56.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
          </group>
          <group name="Top Row" position={[193.76, 262.31, -781.2]}>
            <group name="Master Key Instance 124" position={[-803.2, 0, 0]}>
              <group name="Cap56">
                <mesh
                  name="Text57"
                  geometry={nodes.Text57.geometry}
                  material={materials['Text57 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube57"
                  geometry={nodes.Cube57.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 113" position={[-696.21, 0, 0]}>
              <group name="Cap57">
                <mesh
                  name="Text58"
                  geometry={nodes.Text58.geometry}
                  material={materials['Text58 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube58"
                  geometry={nodes.Cube58.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 27" position={[-586.22, 0, 0]}>
              <group name="Cap58">
                <mesh
                  name="Text59"
                  geometry={nodes.Text59.geometry}
                  material={materials['Text59 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube59"
                  geometry={nodes.Cube59.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 154" position={[715.08, 0, 0]}>
              <group name="Cap59">
                <mesh
                  name="Text60"
                  geometry={nodes.Text60.geometry}
                  material={materials['Text60 Material']}
                  castShadow
                  receiveShadow
                  position={[48.17, 34.74, 9.06]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube60"
                  geometry={nodes.Cube60.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[43.01, 15.19, 0]}
                  scale={[1.9, 1, 1]}
                />
              </group>
            </group>
            <group name="Master Key Instance 141" position={[602.06, 0, 0]}>
              <group name="Cap60">
                <mesh
                  name="Text61"
                  geometry={nodes.Text61.geometry}
                  material={materials['Text61 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube61"
                  geometry={nodes.Cube61.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 134" position={[492.9, 0, 0]}>
              <group name="Cap61">
                <mesh
                  name="Text62"
                  geometry={nodes.Text62.geometry}
                  material={materials['Text62 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube62"
                  geometry={nodes.Cube62.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 103" position={[383.05, 0, 0]}>
              <group name="Cap62">
                <mesh
                  name="Text63"
                  geometry={nodes.Text63.geometry}
                  material={materials['Text63 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube63"
                  geometry={nodes.Cube63.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 94" position={[274.72, 0, 0]}>
              <group name="Cap63">
                <mesh
                  name="Text64"
                  geometry={nodes.Text64.geometry}
                  material={materials['Text64 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube64"
                  geometry={nodes.Cube64.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 83" position={[164.76, 0, 0]}>
              <group name="Cap64">
                <mesh
                  name="Text65"
                  geometry={nodes.Text65.geometry}
                  material={materials['Text65 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube65"
                  geometry={nodes.Cube65.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 74" position={[58.88, 0, 0]}>
              <group name="Cap65">
                <mesh
                  name="Text66"
                  geometry={nodes.Text66.geometry}
                  material={materials['Text66 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube66"
                  geometry={nodes.Cube66.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 63" position={[-49.46, 0, 0]}>
              <group name="Cap66">
                <mesh
                  name="Text67"
                  geometry={nodes.Text67.geometry}
                  material={materials['Text67 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube67"
                  geometry={nodes.Cube67.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 5" position={[-157.79, 0, 0]}>
              <group name="Cap67">
                <mesh
                  name="Text68"
                  geometry={nodes.Text68.geometry}
                  material={materials['Text68 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube68"
                  geometry={nodes.Cube68.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 43" position={[-266.12, 0, 0]}>
              <group name="Cap68">
                <mesh
                  name="Text69"
                  geometry={nodes.Text69.geometry}
                  material={materials['Text69 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube69"
                  geometry={nodes.Cube69.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance 33" position={[-372, 0, 0]}>
              <group name="Cap69">
                <mesh
                  name="Text70"
                  geometry={nodes.Text70.geometry}
                  material={materials['Text70 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube70"
                  geometry={nodes.Cube70.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
            <group name="Master Key Instance3" position={[-479.51, 0, 0]}>
              <group name="Cap70">
                <mesh
                  name="Text71"
                  geometry={nodes.Text71.geometry}
                  material={materials['Text71 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube71"
                  geometry={nodes.Cube71.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
          </group>
          <mesh
            name="Rectangle 4"
            geometry={nodes['Rectangle 4'].geometry}
            material={materials['Rectangle 4 Material']}
            castShadow
            receiveShadow
            position={[194.4, 205.21, -552.51]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={1.28}
          />
          <mesh
            name="Rectangle 41"
            geometry={nodes['Rectangle 41'].geometry}
            material={materials['Rectangle 41 Material']}
            castShadow
            receiveShadow
            position={[196.45, 217.27, -553.48]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          />
          <group name="Template" visible={false} position={[-335.39, 244.22, -297.02]}>
            <group name="Master Key" position={[-48.11, 18.09, 404.52]}>
              <group name="Cap71">
                <mesh
                  name="Text72"
                  geometry={nodes.Text72.geometry}
                  material={materials['Text72 Material']}
                  castShadow
                  receiveShadow
                  position={[-0.84, 34.74, -0.25]}
                  rotation={[-Math.PI / 2, 0, 0]}
                />
                <mesh
                  name="Cube72"
                  geometry={nodes.Cube72.geometry}
                  material={materials['']}
                  castShadow
                  receiveShadow
                  position={[0, 15.19, 0]}
                />
              </group>
            </group>
          </group>
          <directionalLight
            name="Directional Light"
            castShadow
            intensity={0.7}
            shadow-mapSize-width={1024}
            shadow-mapSize-height={1024}
            shadow-camera-near={-10000}
            shadow-camera-far={100000}
            shadow-camera-left={-1000}
            shadow-camera-right={1000}
            shadow-camera-top={1000}
            shadow-camera-bottom={-1000}
            position={[-167.85, 295.01, 300]}
          />
          <OrthographicCamera name="1" makeDefault={true} far={10000} near={-50000} />
          <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
        </scene>
      </group>
    </>
  )
}
