/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 chassis.gltf 
*/


import  { forwardRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useBox } from '@react-three/cannon';



const Chassis = forwardRef(({ args = [1, 1, 4], mass = 500, setVisible, ...props }, ref) => {
  const { nodes, materials } = useGLTF('/chassis.gltf');

  const [, api] = useBox(
    () => ({
      mass,
      args,
      allowSleep: false,
      ...props
    }),
    ref
  );

  return (
    <group {...props} dispose={null} ref={ref} api={api} userData={{ id: 'drifter' }} {...props}>
      <group rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Mesh_body003.geometry} material={materials['plastic.002']} />
        <mesh geometry={nodes.Mesh_body003_1.geometry} material={materials.paintGreen} />
        <mesh geometry={nodes.Mesh_body003_2.geometry} material={materials['lightFront.001']} />
        <mesh geometry={nodes.Mesh_body003_3.geometry} material={materials['_defaultMat.002']} />
        <mesh geometry={nodes.Mesh_body003_4.geometry} material={materials['window.001']} />
        <mesh geometry={nodes.Mesh_body003_5.geometry} material={materials['lightBack.001']} />
    </group>
    </group>
  );

});

useGLTF.preload('/chassis.gltf')

export default Chassis;
